services:
  db:
    image: postgres:15
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5434:5432"
    networks:
      - app_net

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - app_net

  api:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - localstack
    ports:
      - "8000:8000"
    networks:
      - app_net

# Define volumes if needed
volumes:
  pgdata:

# Define networks
networks:
  app_net:
    driver: bridge
