services:
  db:
    image: postgres:15
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
<<<<<<< HEAD
      POSTGRES_DB: blog_db    # <-- changed from app_db to blog_db
=======
      POSTGRES_DB: blog_db
>>>>>>> 6c2e87f4351edda155a678643ed75a5b9f58626d
    ports:
      - "5434:5432"
    networks:
      - app_net

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - app_net

  api:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - localstack
    ports:
      - "8000:8000"
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
