version: "3.9"

services:
  db:
    image: postgres:15
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net
    # 👇 healthcheck so API waits until DB is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    networks:
      - app_net

  api:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy   # 👈 wait until DB healthcheck passes
      localstack:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
